name: Image Analysis with Anthropic's Claude LLM
description: Convert images into text and summarize their content with Anthropic's Claude LLM
author: Cloudera, Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2024-10-01"

environment_variables:
  ANTHROPIC_API_KEY:
    default: ""
    description: "Anthropic API key for Claude access."
    required: true

runtimes:
  - editor: JupyterLab
    kernel: Python 3.11 
    edition: Standard 

tasks:
  - type: run_session
    name: Install Dependencies
    script: 1_session-install-dependencies/download_requirements.py
    short_summary: Install Requirements and Dependencies
    kernel: python3
    cpu: 2
    memory: 8

  - type: start_application
    name: Application Name here
    short_summary: Write a short summary of the app here.
    long_summary: Write a longer summary about the app here.
    subdomain: pick-a-domain-here
    script: 2_app/app.py
    environment_variables:
      TASK_TYPE: START_APPLICATION